### ISSUE TITLE
Two spec-compliant SDKs

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/spec#86]
There are unknown unknowns within the spec. We'll know more through SDK implementation. As such, a barrier to a true alpha release would be to get 2 spec-compliant SDKs. I think java is a reasonable proxy for the typed side of things. Python or Javascript would be a good second candidate.

- [x] Spec-compliant Java SDK
- [x] Spec-compliant non-Java SDK (Python? JavaScript?)

**Comment by matthewelwell** [comment]
We have a python implementation in the works [here](https://github.com/open-feature/python-sdk/pull/1) if it helps.

**Comment by justinabrahms** [comment]
Sounds good to me.  Once you hit spec compliance with the parts of the spec in scope for alpha.. check the box. :)

**Comment by weyert** [comment]
Are there plans to also support browser JavaScript beside node?

**Comment by justinabrahms** [comment]
@weyert Yes. We think there will be a single SDK, but the providers themselves will differ. I suspect help is welcome there if you're interested in getting involved.

**Comment by justinabrahms** [comment]
I support this.

**Comment by toddbaert** [comment]
Here's what I've put in the Node.JS readme, just a rephrase of above:

```
- [x] spec compliant
- [x] contains test suite which verifies behavior consistent with spec
- [x] contains test suite with reasonable coverage
- [x] automated publishing
- [ ] comprehensive readme
```

**Comment by toddbaert** [comment]
cc @davejohnston @dabeeeenster @ajhelsby 

I'm OK to close this now if you agree. I'm going to work a bit on the Node.JS readme, and also https://github.com/open-feature/spec/issues/101, which is related, and should benefit all the SDKs.
